"""add_document_fields_to_reviews

Revision ID: 0af7e5f06a95
Revises: 791bee0dcbb8
Create Date: 2025-09-06 13:53:57.924521

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0af7e5f06a95'
down_revision = '791bee0dcbb8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.add_column(sa.Column('has_document', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('document_filename', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('document_path', sa.String(length=500), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.drop_column('document_path')
        batch_op.drop_column('document_filename')
        batch_op.drop_column('has_document')

    # ### end Alembic commands ###
