"""adding indices to comment table

Revision ID: 1c557d0dd0c8
Revises: ab78086b063a
Create Date: 2026-03-17 06:24:11.476281

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "1c557d0dd0c8"
down_revision = "ab78086b063a"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("review_comments", schema=None) as batch_op:
        batch_op.create_index(
            "ix_review_comments_review_created",
            ["review_id", "created_at"],
            unique=False,
        )
        batch_op.create_index(
            "ix_review_comments_review_id", ["review_id"], unique=False
        )
        batch_op.create_index(
            "ix_review_comments_review_parent",
            ["review_id", "parent_comment_id"],
            unique=False,
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("review_comments", schema=None) as batch_op:
        batch_op.drop_index("ix_review_comments_review_parent")
        batch_op.drop_index("ix_review_comments_review_id")
        batch_op.drop_index("ix_review_comments_review_created")

    # ### end Alembic commands ###
