"""revising columns in movies

Revision ID: 2f6909619958
Revises: 81dd26793a46
Create Date: 2025-03-15 13:17:36.368766

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2f6909619958'
down_revision = '81dd26793a46'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('movies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('original_language', sa.String(length=10), nullable=False))
        batch_op.add_column(sa.Column('original_title', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('overview', sa.Text(), nullable=False))
        batch_op.add_column(sa.Column('release_date', sa.Date(), nullable=False))
        batch_op.drop_column('description')
        batch_op.drop_column('trailer')

    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.create_foreign_key(batch_op.f('fk_reviews_movie_id_movies'), 'movies', ['movie_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_reviews_movie_id_movies'), type_='foreignkey')

    with op.batch_alter_table('movies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('trailer', sa.VARCHAR(length=500), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('description', sa.TEXT(), autoincrement=False, nullable=False))
        batch_op.drop_column('release_date')
        batch_op.drop_column('overview')
        batch_op.drop_column('original_title')
        batch_op.drop_column('original_language')

    # ### end Alembic commands ###
