"""changing user information from mandatory to optional

Revision ID: 3553715e6db5
Revises: 64d19748bac2
Create Date: 2026-03-13 11:59:31.039150

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "3553715e6db5"
down_revision = "64d19748bac2"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.alter_column("first_name", existing_type=sa.VARCHAR(), nullable=True)
        batch_op.alter_column("last_name", existing_type=sa.VARCHAR(), nullable=True)
        batch_op.alter_column("zipcode", existing_type=sa.VARCHAR(), nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.alter_column("zipcode", existing_type=sa.VARCHAR(), nullable=False)
        batch_op.alter_column("last_name", existing_type=sa.VARCHAR(), nullable=False)
        batch_op.alter_column("first_name", existing_type=sa.VARCHAR(), nullable=False)

    # ### end Alembic commands ###
