"""adding show_review_backdrop column to reviews table

Revision ID: 458520e8f57c
Revises: 667841d4c270
Create Date: 2026-03-22 11:45:42.882512

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "458520e8f57c"
down_revision = "667841d4c270"
branch_labels = None
depends_on = None


def upgrade():
    # NOT NULL + existing rows: need a DB-level default at add time; ORM default=True alone is not enough.
    with op.batch_alter_table("reviews", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "show_review_backdrop",
                sa.Boolean(),
                nullable=False,
                server_default=sa.true(),
            )
        )


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("reviews", schema=None) as batch_op:
        batch_op.drop_column("show_review_backdrop")

    # ### end Alembic commands ###
