"""adding review comments table

Revision ID: 5aa2000eaa1f
Revises: f102d09a09dd
Create Date: 2026-03-12 08:07:35.573853

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5aa2000eaa1f'
down_revision = 'f102d09a09dd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('review_comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('review_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('parent_comment_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['parent_comment_id'], ['review_comments.id'], name=op.f('fk_review_comments_parent_comment_id_review_comments')),
    sa.ForeignKeyConstraint(['review_id'], ['reviews.id'], name=op.f('fk_review_comments_review_id_reviews')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_review_comments_user_id_users')),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('review_comments')
    # ### end Alembic commands ###
