"""adding options for user profiles

Revision ID: 64d19748bac2
Revises: 5aa2000eaa1f
Create Date: 2026-03-13 07:58:31.382419

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '64d19748bac2'
down_revision = '5aa2000eaa1f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_admin', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('dark_mode', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('icon_color', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('icon_color')
        batch_op.drop_column('dark_mode')
        batch_op.drop_column('is_admin')

    # ### end Alembic commands ###
