"""adding main cast and line notes to review model

Revision ID: 667841d4c270
Revises: cc028bf8dfc5
Create Date: 2026-03-21 10:44:14.049894

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "667841d4c270"
down_revision = "cc028bf8dfc5"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("reviews", schema=None) as batch_op:
        batch_op.add_column(sa.Column("main_cast", sa.Text(), nullable=True))
        batch_op.add_column(sa.Column("line_notes", sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("reviews", schema=None) as batch_op:
        batch_op.drop_column("line_notes")
        batch_op.drop_column("main_cast")

    # ### end Alembic commands ###
