"""adding fields to the director table

Revision ID: 680ea3b0ad39
Revises: add_external_id_to_directors
Create Date: 2026-03-07 08:32:16.309765

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '680ea3b0ad39'
down_revision = 'add_external_id_to_directors'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('directors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cover_photo', sa.String(length=500), nullable=False))
        batch_op.drop_index('ix_directors_external_id')
        batch_op.create_unique_constraint(None, ['external_id'])

    with op.batch_alter_table('movies', schema=None) as batch_op:
        batch_op.drop_index('ix_movies_director_id')

    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.drop_index('ix_reviews_director_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.create_index('ix_reviews_director_id', ['director_id'], unique=False)

    with op.batch_alter_table('movies', schema=None) as batch_op:
        batch_op.create_index('ix_movies_director_id', ['director_id'], unique=False)

    with op.batch_alter_table('directors', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_index('ix_directors_external_id', ['external_id'], unique=True)
        batch_op.drop_column('cover_photo')

    # ### end Alembic commands ###
