"""adding short text

Revision ID: 791bee0dcbb8
Revises: 2f6909619958
Create Date: 2025-04-20 15:36:47.796177

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '791bee0dcbb8'
down_revision = '2f6909619958'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('review_tags',
    sa.Column('review_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['review_id'], ['reviews.id'], name=op.f('fk_review_tags_review_id_reviews')),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], name=op.f('fk_review_tags_tag_id_tags')),
    sa.PrimaryKeyConstraint('review_id', 'tag_id')
    )
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.alter_column('movie_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.alter_column('movie_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    op.drop_table('review_tags')
    op.drop_table('tags')
    # ### end Alembic commands ###
