"""adding backdrops to movie and director models

Revision ID: 89571b7dcc43
Revises: 680ea3b0ad39
Create Date: 2026-03-08 09:47:01.691705

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "89571b7dcc43"
down_revision = "680ea3b0ad39"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("directors", schema=None) as batch_op:
        batch_op.add_column(sa.Column("backdrop", sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column("description", sa.Text(), nullable=True))

    with op.batch_alter_table("movies", schema=None) as batch_op:
        batch_op.add_column(sa.Column("backdrop", sa.String(length=500), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("movies", schema=None) as batch_op:
        batch_op.drop_column("backdrop")

    with op.batch_alter_table("directors", schema=None) as batch_op:
        batch_op.drop_column("description")
        batch_op.drop_column("backdrop")

    # ### end Alembic commands ###
