"""adding notification capabilities

Revision ID: ab78086b063a
Revises: a453f790c2db
Create Date: 2026-03-15 20:17:29.775052

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "ab78086b063a"
down_revision = "a453f790c2db"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "notification_reads",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("event_type", sa.String(length=20), nullable=False),
        sa.Column("event_id", sa.Integer(), nullable=False),
        sa.Column("read_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_notification_reads_user_id_users")
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "user_id", "event_type", "event_id", name="uq_notification_read_user_event"
        ),
    )
    with op.batch_alter_table("comment_likes", schema=None) as batch_op:
        batch_op.add_column(sa.Column("created_at", sa.DateTime(), nullable=False))

    with op.batch_alter_table("review_likes", schema=None) as batch_op:
        batch_op.add_column(sa.Column("created_at", sa.DateTime(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("review_likes", schema=None) as batch_op:
        batch_op.drop_column("created_at")

    with op.batch_alter_table("comment_likes", schema=None) as batch_op:
        batch_op.drop_column("created_at")

    op.drop_table("notification_reads")
    # ### end Alembic commands ###
