"""add document fields to reviews

Revision ID: add_document_fields
Revises: 791bee0dcbb8
Create Date: 2025-01-27 12:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'add_document_fields_001'
down_revision = '791bee0dcbb8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.add_column(sa.Column('has_document', sa.Boolean(), nullable=False, server_default='false'))
        batch_op.add_column(sa.Column('document_filename', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('document_path', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('document_type', sa.String(length=10), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.drop_column('document_type')
        batch_op.drop_column('document_path')
        batch_op.drop_column('document_filename')
        batch_op.drop_column('has_document')
    # ### end Alembic commands ###
