"""add directors and links

Revision ID: bebcf6ae4f08
Revises: add_search_indexes
Create Date: 2025-09-30 07:07:38.221801

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "bebcf6ae4f08"
down_revision = "add_search_indexes"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "directors",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("biography", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("movies", schema=None) as batch_op:
        batch_op.add_column(sa.Column("director_id", sa.Integer(), nullable=True))
        batch_op.drop_index("idx_movie_external_id")
        batch_op.drop_index("idx_movie_original_title_gin", postgresql_using="gin")
        batch_op.drop_index("idx_movie_overview_gin", postgresql_using="gin")
        batch_op.drop_index("idx_movie_release_date")
        batch_op.drop_index("idx_movie_title_gin", postgresql_using="gin")
        batch_op.create_foreign_key(
            batch_op.f("fk_movies_director_id_directors"),
            "directors",
            ["director_id"],
            ["id"],
        )

    with op.batch_alter_table("reviews", schema=None) as batch_op:
        batch_op.add_column(sa.Column("director_id", sa.Integer(), nullable=True))
        batch_op.drop_index("idx_review_content_type")
        batch_op.drop_index("idx_review_date_added")
        batch_op.drop_index("idx_review_description_gin", postgresql_using="gin")
        batch_op.drop_index("idx_review_movie_id")
        batch_op.drop_index("idx_review_rating")
        batch_op.drop_index("idx_review_text_gin", postgresql_using="gin")
        batch_op.drop_index("idx_review_title_gin", postgresql_using="gin")
        batch_op.create_foreign_key(
            batch_op.f("fk_reviews_director_id_directors"),
            "directors",
            ["director_id"],
            ["id"],
        )

    with op.batch_alter_table("tags", schema=None) as batch_op:
        batch_op.drop_index("idx_tag_name_gin", postgresql_using="gin")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("tags", schema=None) as batch_op:
        batch_op.create_index(
            "idx_tag_name_gin", ["name"], unique=False, postgresql_using="gin"
        )

    with op.batch_alter_table("reviews", schema=None) as batch_op:
        batch_op.drop_constraint(
            batch_op.f("fk_reviews_director_id_directors"), type_="foreignkey"
        )
        batch_op.create_index(
            "idx_review_title_gin", ["title"], unique=False, postgresql_using="gin"
        )
        batch_op.create_index(
            "idx_review_text_gin", ["review_text"], unique=False, postgresql_using="gin"
        )
        batch_op.create_index("idx_review_rating", ["rating"], unique=False)
        batch_op.create_index("idx_review_movie_id", ["movie_id"], unique=False)
        batch_op.create_index(
            "idx_review_description_gin",
            ["description"],
            unique=False,
            postgresql_using="gin",
        )
        batch_op.create_index("idx_review_date_added", ["date_added"], unique=False)
        batch_op.create_index("idx_review_content_type", ["content_type"], unique=False)
        batch_op.drop_column("director_id")

    with op.batch_alter_table("movies", schema=None) as batch_op:
        batch_op.drop_constraint(
            batch_op.f("fk_movies_director_id_directors"), type_="foreignkey"
        )
        batch_op.create_index(
            "idx_movie_title_gin", ["title"], unique=False, postgresql_using="gin"
        )
        batch_op.create_index("idx_movie_release_date", ["release_date"], unique=False)
        batch_op.create_index(
            "idx_movie_overview_gin", ["overview"], unique=False, postgresql_using="gin"
        )
        batch_op.create_index(
            "idx_movie_original_title_gin",
            ["original_title"],
            unique=False,
            postgresql_using="gin",
        )
        batch_op.create_index("idx_movie_external_id", ["external_id"], unique=False)
        batch_op.drop_column("director_id")

    op.drop_table("directors")
    # ### end Alembic commands ###
