"""adding indices to several tables

Revision ID: cc028bf8dfc5
Revises: 1c557d0dd0c8
Create Date: 2026-03-17 06:26:57.761710

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "cc028bf8dfc5"
down_revision = "1c557d0dd0c8"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("comment_likes", schema=None) as batch_op:
        batch_op.create_index(
            "ix_comment_likes_comment_id", ["comment_id"], unique=False
        )
        batch_op.create_index(
            "ix_comment_likes_user_comment", ["user_id", "comment_id"], unique=False
        )

    with op.batch_alter_table("movies", schema=None) as batch_op:
        batch_op.create_index("ix_movies_director_id", ["director_id"], unique=False)
        batch_op.create_index("ix_movies_release_date", ["release_date"], unique=False)

    with op.batch_alter_table("notification_reads", schema=None) as batch_op:
        batch_op.create_index(
            "ix_notification_reads_user_id", ["user_id"], unique=False
        )

    with op.batch_alter_table("review_likes", schema=None) as batch_op:
        batch_op.create_index("ix_review_likes_review_id", ["review_id"], unique=False)
        batch_op.create_index(
            "ix_review_likes_user_review", ["user_id", "review_id"], unique=False
        )

    with op.batch_alter_table("reviews", schema=None) as batch_op:
        batch_op.create_index(
            "ix_reviews_content_type_date", ["content_type", "date_added"], unique=False
        )
        batch_op.create_index("ix_reviews_director_id", ["director_id"], unique=False)
        batch_op.create_index("ix_reviews_movie_id", ["movie_id"], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("reviews", schema=None) as batch_op:
        batch_op.drop_index("ix_reviews_movie_id")
        batch_op.drop_index("ix_reviews_director_id")
        batch_op.drop_index("ix_reviews_content_type_date")

    with op.batch_alter_table("review_likes", schema=None) as batch_op:
        batch_op.drop_index("ix_review_likes_user_review")
        batch_op.drop_index("ix_review_likes_review_id")

    with op.batch_alter_table("notification_reads", schema=None) as batch_op:
        batch_op.drop_index("ix_notification_reads_user_id")

    with op.batch_alter_table("movies", schema=None) as batch_op:
        batch_op.drop_index("ix_movies_release_date")
        batch_op.drop_index("ix_movies_director_id")

    with op.batch_alter_table("comment_likes", schema=None) as batch_op:
        batch_op.drop_index("ix_comment_likes_user_comment")
        batch_op.drop_index("ix_comment_likes_comment_id")

    # ### end Alembic commands ###
