"""adding backdrop image to reviews model

Revision ID: f102d09a09dd
Revises: 89571b7dcc43
Create Date: 2026-03-08 10:57:49.052852

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "f102d09a09dd"
down_revision = "89571b7dcc43"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("reviews", schema=None) as batch_op:
        batch_op.add_column(sa.Column("backdrop", sa.String(length=500), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("reviews", schema=None) as batch_op:
        batch_op.drop_column("backdrop")

    # ### end Alembic commands ###
